import type { Metadata } from "next";
import LocalFont from 'next/font/local'
import "./globals.css";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const Vazir = LocalFont({
  src: '../public/font/vazir.woff2'
})

const yekan = LocalFont({
  src:'../public/font/yekan.ttf'
})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa" dir="rtl">
      <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200&icon_names=search" />
      <body
        className={`bg-lime-800 ${Vazir.className}`}
      >
        <main className="">
          {children}
        </main>
      </body>
    </html>
  );
}
